export const LOAD_NEWS_START = 'LOAD_NEWS_START';
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS';
export const LOAD_NEWS_ERROR = 'LOAD_NEWS_ERROR';

export const LOAD_NEWS_ITEM_SUCCESS = 'LOAD_NEWS_ITEM_SUCCESS';

export const LOAD_COMMENT_SUCCESS = 'LOAD_COMMENT_SUCCESS';
