export const ITEM_ADD = 'ITEM_ADD';
export const ITEM_LOADER_ON = 'ITEM_LOADER_ON';
export const ITEM_LOADER_OFF = 'ITEM_LOADER_OFF';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';

export const COMMENTS_LOADER_ON = 'COMMENTS_LOADER_ON';
export const COMMENTS_LOADER_OFF = 'COMMENTS_LOADER_OFF';

export const LOAD_ITEMS = 'LOAD_ITEMS';
export const ITEMS_LOADER_ON = 'ITEMS_LOADER_ON';
export const ITEMS_LOADER_OFF = 'ITEMS_LOADER_OFF';
