export const LOAD_STORIES = 'LOAD_STORIES';
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS';

export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';

export const LOAD_STORY = 'LOAD_STORY';
export const LOAD_STORY_SUCCESS = 'LOAD_STORY_SUCCESS';
